
WEBSOCKET ws://localhost:8000/table/abc/player/a1
Content-Type: application/json
===
=== wait-for-server

###
WEBSOCKET ws://localhost:8000/table/abc/player/b2
Content-Type: application/json
===
=== wait-for-server

